#!/bin/bash
iamspeed
xrandr --output HDMI2 --left-of HDMI1
feh --bg-scale .config/i3/wallpapers/fullwall.jpg 
picom &
# repeat until xinput returns success for the first time
while ! xinput set-prop 13 "libinput Tapping Enabled" 1
do
    sleep 1
done
discord --start-minimized
